license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Moo of Doom transforms ordinary cows into absurdly overpowered entities.
OP cows fight hostile mobs, drop rare loot, grant aura buffs, and exhibit
chaotic behaviors like teleportation, random explosions, and moon jumps.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
